### ISSUE TITLE
Is micromamba supported?

### ISSUE THREAD

**Issue by acampove** [conda-forge/root-feedstock#240]
### Comment:

Hi, 

I am not sure if this is a problem with ROOT or conda or mamba or micromamba. I am trying to install root in micro mamba with:

```bash
micromamba create -n test_001 root root_base
```

and I see:

```
bin/micromamba
[+] 1.3s
conda-forge/linux-64 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  12.9MB /  33.8MB @  10.5MB/s  1.3s
conda-forge/noarch   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━  11.5MB /  14.3MB @   9.3MB/s  1.3sterminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./rxe_run_toys: line 50: 23101 Aborted                 (core dumped) ( "/publicfs/ucas/user/campoverde/Test/Jobdir/extractor/001_001/bin/micromamba" "${@}" )
[E 240417 17:47:05 rxe_local:67] Process returned exit status: 134
Traceback (most recent call last):
  File "/publicfs/ucas/user/campoverde/Packages/mambaforge/envs/rk/bin/rxe_local", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/publicfs/ucas/user/campoverde/Packages/RK/rk_extractor/scripts/jobs/rxe_local", line 85, in <module>
    main()
  File "/publicfs/ucas/user/campoverde/Packages/RK/rk_extractor/scripts/jobs/rxe_local", line 82, in main
    run()
  File "/publicfs/ucas/user/campoverde/Packages/RK/rk_extractor/scripts/jobs/rxe_local", line 68, in run
    raise
RuntimeError: No active exception to reraise
```

can ROOT be used with micromamba?

Cheers.

**Comment by matthewfeickert** [comment]
@acampove Yes. All conda package installers (`conda`, `mamba`, `micromamba`, `pixi`, ...) support installing from conda-forge.
