### ISSUE TITLE
ROOT needs to be updated for dependent packages to rerender

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/root-feedstock#273]
As ROOT hasn't been rerendered and seem to lock down the compiler versions, as conda-forge continues to maintain and develop the rest of the ecosystem it has made it so that any package that depends on ROOT can not be properly built or rerendered.

Examples:
* Delphes: https://github.com/conda-forge/delphes-feedstock/pull/3#issuecomment-2544320063
* YODA: https://github.com/conda-forge/yoda-feedstock
* Rivet: I can't submit a working PR to https://github.com/conda-forge/staged-recipes for Rivet given the same issues.

@conda-forge/root, in 2025 is there a timeline or plan to support conda-forge builds from the ROOT team?

**Comment by matthewfeickert** [comment]
Note in PR #275 the recipe can't even be rerendered as it isn't valid:

```
Traceback (most recent call last):
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/linter/lints.py", line 1026, in lint_recipe_is_parsable
    CondaMetaYAML(recipe_text)
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_forge_tick/recipe_parser/_parser.py", line 579, in __init__
    v, e = _parse_jinja2_variables(meta_yaml)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_forge_tick/recipe_parser/_parser.py", line 114, in _parse_jinja2_variables
    and _line_is_only_selector(all_nodes[i + 1].nodes[0].data.strip())
                               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'If' object has no attribute 'nodes'
2024-12-16 02:04:47,748 WARNING  conda_smithy.linter.lints || Error parsing recipe with conda-recipe-manager: ParserError('while parsing a flow mapping', <yaml._yaml.Mark object at 0x7f898b9a8f90>, "did not find expected ',' or '}'", <yaml._yaml.Mark object at 0x7f898b9a8fe0>)
Traceback (most recent call last):
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_recipe_manager/parser/recipe_reader.py", line 109, in _parse_yaml
    output = _sub_jinja(cast(JsonType, yaml.load(s, Loader=SafeLoader)))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 844, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 847, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 1, column 11
did not find expected ',' or '}'
  in "<unicode string>", line 1, column 92

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/linter/lints.py", line 1069, in lint_recipe_is_parsable
    RecipeParser(recipe_text)
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_recipe_manager/parser/recipe_reader.py", line 435, in __init__
    new_node = RecipeReader._parse_line_node(clean_line)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_recipe_manager/parser/recipe_reader.py", line 142, in _parse_line_node
    output = RecipeReader._parse_yaml(s)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_recipe_manager/parser/recipe_reader.py", line 126, in _parse_yaml
    cast(JsonType, yaml.load(s, Loader=SafeLoader)), lambda d: substitute_markers(d, sub_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 844, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 847, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 1, column 11
did not find expected ',' or '}'
  in "<unicode string>", line 1, column 92
```

**Comment by nsmith-** [comment]
I'm also running into this issue while preparing a new recipe for CMS Combine. Locally running `python3 build-locally.py osx_arm64` I end up at
```
The following packages are incompatible
├─ libcxx >=18 * is requested and can be installed;
└─ root =* * is not installable because there are no viable options
   ├─ root [6.22.6|6.22.8|6.24.0] would require
   │  └─ root_base [==6.22.6 py38h1381eaf_0|==6.22.6 py39hcbb6425_0|...|==6.24.0 py39hdf834e2_0], which requires
   │     └─ libcxx >=11,<12.0a0 *, which conflicts with any installable versions previously reported;
   ├─ root [6.26.10|6.26.2|6.26.4|6.26.6|6.26.8] would require
   │  └─ root_base [==6.26.10 py310he39f453_1|==6.26.10 py311h26794ff_1|...|==6.26.8 py39h611b57b_1], which requires
   │     └─ libcxx >=14,<15.0a0 *, which conflicts with any installable versions previously reported;
   ├─ root 6.28.0 would require
   │  └─ root_base [==6.28.0 py310h0c5752d_0|==6.28.0 py310he3e615b_1|...|==6.28.0 py39ha7d3e57_1], which requires
   │     └─ libcxx >=15,<16.0a0 *, which conflicts with any installable versions previously reported;
   ├─ root [6.28.10|6.28.12|6.28.4|6.30.2|6.30.4] would require
   │  └─ root_base [==6.28.10 py310h44eaee5_0|==6.28.10 py310h44eaee5_2|...|==6.30.4 py39h5968530_0], which requires
   │     └─ libcxx >=16,<17.0a0 *, which conflicts with any installable versions previously reported;
   ├─ root 6.32.0 would require
   │  └─ root_base [==6.32.0 py310hc0d634b_0|==6.32.0 py312hef6964a_0|==6.32.0 py38h5ae74bb_0|==6.32.0 py39he7856a1_0], which requires
   │     └─ libcxx >=17,<18.0a0 *, which conflicts with any installable versions previously reported;
   ├─ root [6.24.6|6.26.2] would require
   │  └─ root_base [==6.24.6 py310h186c2fd_3|==6.24.6 py310h6d57595_2|...|==6.26.2 py39h2ec9a04_2], which requires
   │     └─ libcxx >=13,<14.0a0 *, which conflicts with any installable versions previously reported;
   └─ root [6.24.6|6.26.0] would require
      └─ root_base [==6.24.6 py310h41e58fc_1|==6.24.6 py38h1a1db37_0|...|==6.26.0 py39hd7d9cc8_0], which requires
         └─ libcxx >=12,<13.0a0 *, which conflicts with any installable versions previously reported.
```

On the other hand I am able to get a solved environment for `osx`, but clearly the version pinning here is making it challenging to develop.

**Comment by matthewfeickert** [comment]
If @conda-forge/root could take a look at fixing a rerender of the current feedstock https://github.com/conda-forge/root-feedstock/pull/275 that would be helpful.

**Comment by matthewfeickert** [comment]
This has been resolved by @chrisburr. Thank you, Chris!
