### ISSUE TITLE
PyROOT and Notebook Fail to Load

### ISSUE THREAD

**Issue by nathanknshg** [conda-forge/root-feedstock#42]
Issue:

After installation by the instructions, I am unable to <code> import ROOT </code> in python or run <code> root --notebook </code> on Ubuntu 18.04 LTS. The following is the terminal output when I try. Just running <code> root </code> on its own works perfectly. 

<details>

```
(std) nk42@MXP:~/workspace$ conda activate root_env
(root_env) nk42@MXP:~/workspace$ root
   ------------------------------------------------------------
  | Welcome to ROOT 6.18/00                  https://root.cern |
  |                               (c) 1995-2019, The ROOT Team |
  | Built for linuxx8664gcc on Jun 29 2019, 20:36:00           |
  | From tag , 25 June 2019                                    |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

root [0] .demo
root [1] .q

Taking a break from ROOT? Hope to see you back!

(root_env) nk42@MXP:~/workspace$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
Error in <TCling::RegisterModule>: cannot find dictionary module libPyROOT_rdict.pcm
>>> quit()
(root_env) nk42@MXP:~/workspace$ root --notebook
Traceback (most recent call last):
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 864, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nk42/miniconda3/envs/root_env/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/home/nk42/miniconda3/envs/root_env/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
(root_env) nk42@MXP:~/workspace$

```
</details>

One thing I could note is that I am running it on the windows linux subsystem, but I also tried the python import test on a pure Ubuntu machine with the same issue.

I also tried with python 2.7 with no influence on the error.

This is an amazing way to install root and I hope to get to use it.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /home/nk42/miniconda3/envs/std:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_tflow_select             2.3.0                       mkl
absl-py                   0.7.1                    py37_0
afterimage                1.21              hf014aae_1002    conda-forge
astor                     0.7.1                    py37_0
attrs                     19.1.0                   py37_1
backcall                  0.1.0                    py37_0
binutils                  1.0.1                         0    conda-forge
binutils_impl_linux-64    2.31.1               h6176602_1
binutils_linux-64         2.31.1               h6176602_7
blas                      2.10                   openblas    conda-forge
bleach                    3.1.0                    py37_0
c-ares                    1.15.0               h7b6447c_1
c-compiler                1.0.1                h14c3975_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cfitsio                   3.430             h0bd2449_1002    conda-forge
compilers                 1.0.1                         0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cxx-compiler              1.0.1                h6bb024c_0    conda-forge
cycler                    0.10.0                   py37_0
davix                     0.7.4                hb54d6fb_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
expat                     2.2.6                he6710b0_0
fftw                      3.3.8           mpi_mpich_h3f9e1be_1006    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
fortran-compiler          1.0.1                h0e1e685_0    conda-forge
freetype                  2.9.1                h8a8886c_1
gast                      0.2.2                    py37_0
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_7    conda-forge
gdk-pixbuf                2.36.12           h7a26e22_1003    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_1
gfortran_linux-64         7.3.0                h553295d_7
giflib                    5.1.7                h516909a_1    conda-forge
glew                      2.0.0             hf484d3e_1002    conda-forge
glib                      2.58.3            h6f030ca_1001    conda-forge
gmp                       6.1.2                h6c8ec71_1
gobject-introspection     1.58.2          py37h5503ade_1001    conda-forge
google-pasta              0.1.7                      py_0
graphite2                 1.3.13            hf484d3e_1000    conda-forge
graphviz                  2.40.1               h0dab3d1_0    conda-forge
grpcio                    1.16.1           py37hf8bcb03_1
gsl                       2.5                  h294904e_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_7    conda-forge
h5py                      2.9.0            py37h7918eee_0
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf5                      1.10.4               hb1b8bf9_0
icu                       58.2                 h9c2bf20_1
intel-openmp              2019.4                      243
ipykernel                 5.1.1            py37h39e3cac_0
ipython                   7.6.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
jedi                      0.13.3                   py37_0
jinja2                    2.10.1                   py37_0
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.1                    py37_0
jupyter_client            5.2.4                    py37_0
jupyter_core              4.5.0                      py_0
jupyterlab                0.35.5           py37hf63ae98_0
jupyterlab_server         0.2.0                    py37_0
keras                     2.2.4                         0
keras-applications        1.0.8                      py_0
keras-base                2.2.4                    py37_0
keras-preprocessing       1.1.0                      py_1
kiwisolver                1.1.0            py37he6710b0_0
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcroco                  0.6.13               h8d621e5_0    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libglu                    9.0.0             hf484d3e_1000    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
liblapacke                3.8.0               10_openblas    conda-forge
libopenblas               0.3.6                h6e990d7_4    conda-forge
libpng                    1.6.37               hbc83047_0
libprotobuf               3.8.0                hd408876_0
librsvg                   2.44.14              h11c8777_0    conda-forge
libsodium                 1.0.16               h1bed415_0
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.0.10            h57b8799_1003    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                hea5a465_1
lz4                       2.1.9            py37hd79334b_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37h7b6447c_0
matplotlib                3.1.0            py37h5429711_0
metakernel                0.24.2                     py_0    conda-forge
mistune                   0.8.4            py37h7b6447c_0
mkl                       2019.4                      243
mkl_fft                   1.0.13           py37h516909a_1    conda-forge
mkl_random                1.0.4            py37hf2d7682_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1             hc99cbb1_1012    conda-forge
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0                    py37_0
ncurses                   6.1                  he6710b0_1
notebook                  5.7.8                    py37_0
numpy                     1.16.4           py37h99e49ec_0
numpy-base                1.16.4           py37h2f8d375_0
openblas                  0.3.6                h6e990d7_4    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
pango                     1.40.14           he7ab937_1005    conda-forge
parso                     0.5.0                      py_0
pcre                      8.43                 he6710b0_0
pexpect                   4.7.0                    py37_0
pickleshare               0.7.5                    py37_0
pip                       19.1.1                   py37_0
pixman                    0.38.0            h516909a_1003    conda-forge
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.9                    py37_0
protobuf                  3.8.0            py37he6710b0_0
ptyprocess                0.6.0                    py37_0
pygments                  2.4.2                      py_0
pyparsing                 2.4.0                      py_0
pyqt                      5.9.2            py37h05f1152_2
pyrsistent                0.14.11          py37h7b6447c_0
pythia8                   8.240            py37he1b5a44_2    conda-forge
python                    3.7.3                h0371630_0
python-dateutil           2.8.0                    py37_0
pytz                      2019.1                     py_0
pyyaml                    5.1.1            py37h7b6447c_0
pyzmq                     18.0.0           py37he6710b0_0
qt                        5.9.7                h52cfd70_2    conda-forge
readline                  7.0                  h7b6447c_5
root                      6.18.00         py37h4d53dcf_15    conda-forge
scipy                     1.3.0            py37h921218d_0    conda-forge
send2trash                1.5.0                    py37_0
setuptools                41.0.1                   py37_0
sip                       4.19.8           py37hf484d3e_0
six                       1.12.0                   py37_0
sqlite                    3.28.0               h7b6447c_0
tbb                       2019.7               hc9558a2_0    conda-forge
tbb-devel                 2019.7               hc9558a2_0    conda-forge
tensorboard               1.14.0           py37hf484d3e_0
tensorflow                1.14.0          mkl_py37h45c423b_0
tensorflow-base           1.14.0          mkl_py37h7ce6ba3_0
tensorflow-estimator      1.14.0                     py_0
termcolor                 1.1.0                    py37_1
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.9             hed695b0_1002    conda-forge
tornado                   6.0.3            py37h7b6447c_0
traitlets                 4.3.2                    py37_0
vdt                       0.4.3                hf484d3e_0    conda-forge
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.15.4                     py_0
wheel                     0.33.4                   py37_0
wrapt                     1.11.2           py37h7b6447c_0
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxcursor           1.2.0                h14c3975_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxft               2.3.3                h71203ad_0    conda-forge
xorg-libxpm               3.5.12            h14c3975_1002    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xrootd                    4.9.1            py37h1b6aa1e_0    conda-forge
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zeromq                    4.3.1                he6710b0_3
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.0                h3b9ef0a_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : std
    active env location : /home/nk42/miniconda3/envs/std
            shell level : 2
       user config file : /home/nk42/.condarc
 populated config files :
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /home/nk42/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/nk42/miniconda3/pkgs
                          /home/nk42/.conda/pkgs
       envs directories : /home/nk42/miniconda3/envs
                          /home/nk42/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.4.0-17134-Microsoft ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by chrisburr** [comment]
Thanks for reporting! 🎉 

I know what's causing the import error and it will be fixed in the next few hours. From quickly testing it looks like it might be a harmless error so it shouldn't stop you from using ROOT.

For Jupyter, can you try running `jupyter notebook` instead of `root --notebook`? The ROOT kernel should be available there so there is no need to use the `--notebook` option. (Or you could also install `jupyterlab` and run `jupyter lab` which is the newer version of Jupyter.)

**Comment by nathanknshg** [comment]
The <code> jupyter notebook </code> and <code> jupyter lab </code> options both work. I did still get the same <code> module libPyROOT_rdict.pcm </code> error but it didn't appear to affect the functionality as I was able to plot test histograms without issue.

<details>

```
(std) nk42@MXP:~/workspace$ jupyter lab --no-browser
[I 06:07:18.758 LabApp] JupyterLab extension loaded from /home/nk42/miniconda3/envs/std/lib/python3.7/site-packages/jupyterlab
[I 06:07:18.760 LabApp] JupyterLab application directory is /home/nk42/miniconda3/envs/std/share/jupyter/lab
[W 06:07:18.762 LabApp] JupyterLab server extension not enabled, manually loading...
[I 06:07:18.767 LabApp] JupyterLab extension loaded from /home/nk42/miniconda3/envs/std/lib/python3.7/site-packages/jupyterlab
[I 06:07:18.767 LabApp] JupyterLab application directory is /home/nk42/miniconda3/envs/std/share/jupyter/lab
[I 06:07:18.768 LabApp] Serving notebooks from local directory: /home/nk42/workspace
[I 06:07:18.770 LabApp] The Jupyter Notebook is running at:
[I 06:07:18.770 LabApp] http://localhost:8888/
[I 06:07:18.771 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 06:07:24.018 LabApp] 302 GET / (127.0.0.1) 1.85ms
[W 06:07:24.680 LabApp] Could not determine jupyterlab build status without nodejs
[I 06:07:25.621 LabApp] Kernel started: 20e9cb41-8b2b-42ae-a497-3f46cbe881e2
Error in <TCling::RegisterModule>: cannot find dictionary module libPyROOT_rdict.pcm
[IPKernelApp] ERROR | Can't load '/home/nk42/miniconda3/envs/std/lib/python3.7/site-packages/metakernel/magics/parallel_magic.py': error: No module named 'ipyparallel'
[I 06:07:32.246 LabApp] Adapting to protocol v5.1 for kernel 20e9cb41-8b2b-42ae-a497-3f46cbe881e2
[I 06:07:32.263 LabApp] Adapting to protocol v5.1 for kernel 20e9cb41-8b2b-42ae-a497-3f46cbe881e2
[I 06:09:25.520 LabApp] Saving file at /Untitled.ipynb
```
</details>

**Comment by chrisburr** [comment]
That's reassuring, is `root --notebook` only broken on the Windows Subsystem for Linux? If so it's probably a ROOT bug rather than a conda packaging issue.

Do you have a folder called `.rootnb` in your home directory? Renaming or deleting it might help.

**Comment by nathanknshg** [comment]
I was able to reproduce the <code> root --notebook </code> error on a pure Ubuntu 18.04 machine over ssh. 
<details>
"""
(std) nk42@MXP:~$ ssh ntcuser@lab109
Password:
ntcuser@lab109's password:
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.18.0-22-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

123 packages can be updated.
0 updates are security updates.

Your Hardware Enablement Stack (HWE) is supported until April 2023.
*** System restart required ***
Last login: Mon Jul  8 04:05:18 2019 from 128.171.30.50
(base) ntcuser@ntc-inspiron:~$ conda activate root_env
(root_env) ntcuser@ntc-inspiron:~$ root --notebook
Traceback (most recent call last):
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 864, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ntcuser/miniconda3/envs/root_env/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/home/ntcuser/miniconda3/envs/root_env/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
(root_env) ntcuser@ntc-inspiron:~$
"""
</details>

The error could be caused by the notebook trying to open a browser over ssh or through the subsystem (so I also think it could be a ROOT bug). I typically use the <code> --no-browser </code> flag when starting a jupyter notebook, but things would work without that flag just with an additional inconsequential error. But the  <code> --no-browser </code> flag doesn't seem to do anything for the <code> root --notebook </code> command.

I renamed the <code> .rootnb </code> folder with no change to the error. It seems to rewrite the <code> .rootnb </code> folder.

**Comment by chrisburr** [comment]
Fixed binaries for the PyROOT error message are now deployed so you can update to them.

> I renamed the .rootnb folder with no change to the error. It seems to rewrite the .rootnb folder.

That's expected, ROOT recreates it if it doesn't already exist. As you can get errors if it was made by a different installation. I'd recommend just using Jupyter directly as it will be the same (or better if you use Jupyter lab).

**Comment by nathanknshg** [comment]
Sounds good. Thanks a bunch!

**Comment by chrisburr** [comment]
I asked the ROOT team and the `root --notebook` problem is a known issue will be fixed in the next release of Jupyter notebook. See https://sft.its.cern.ch/jira/browse/ROOT-9920 for details.
